### ISSUE TITLE
The WordPress theme info is getting lost in compressed sass mode

### ISSUE THREAD

**Issue by redundans** [DennisKo/Underscores-Strap#2]
The starting comment in `styles/style.scss` should start with a `!` so that the WordPress theme information will not be trimmed out of the `style.css`, in compressed sass mode. Like below:

```
/*!
Theme Name: _s
Theme URI: http://underscores.me/
...
```

**Comment by christophwolff** [comment]
+1

**Comment by redundans** [comment]
Well, posted a pull request for this easy fix.

https://github.com/DennisKo/Underscores-Strap/pull/3
